fix snyk workflow

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -52,33 +52,41 @@ jobs:
         run: dotnet restore
       - name: Build
         run: dotnet build --configuration Release --no-restore
+
+      - name: Run Snyk to check for vulnerabilities
+        uses: snyk/actions/dotnet@master
+        continue-on-error: true # To make sure that SARIF upload gets called
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        with:
+          args: --sarif-file-output=snyk.sarif
       
         # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
         # Use || true to not fail the pipeline
-      - name: Snyk Code test
-        run: snyk code test --sarif > snyk-code.sarif || true
+      # - name: Snyk Code test
+      #   run: snyk code test --sarif > snyk-code.sarif || true
 
-        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
-      - name: Snyk Open Source monitor
-        run: snyk monitor --all-projects
-        env:
-          # This is where you will need to introduce the Snyk API token created with your Snyk account
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      #   # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
+      # - name: Snyk Open Source monitor
+      #   run: snyk monitor --all-projects
+      #   env:
+      #     # This is where you will need to introduce the Snyk API token created with your Snyk account
+      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
-        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
-        # Use || true to not fail the pipeline.
-      - name: Snyk IaC test and report
-        run: snyk iac test --report || true
+      #   # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
+      #   # Use || true to not fail the pipeline.
+      # - name: Snyk IaC test and report
+      #   run: snyk iac test --report || true
 
-        # Build the docker image for testing
-      - name: Build a Docker image
-        run: docker build -t your/image-to-test .
-        # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
-      - name: Snyk Container monitor
-        run: snyk container monitor your/image-to-test --file=.devcontainer/Dockerfile
+      #   # Build the docker image for testing
+      # - name: Build a Docker image
+      #   run: docker build -t your/image-to-test .
+      #   # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
+      # - name: Snyk Container monitor
+      #   run: snyk container monitor your/image-to-test --file=.devcontainer/Dockerfile
 
         # Push the Snyk Code results into GitHub Code Scanning tab
       - name: Upload result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v2
         with:
-          sarif_file: snyk-code.sarif
+          sarif_file: snyk.sarif
